name: Test-CI
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
env:
  AWS_REGION: ap-northeast-1
jobs:
  actor:
    runs-on: ubuntu-22.04
    steps:
      - name: Check actor
        run: |
          echo "Actor: ${{ github.actor }}"
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Read Secret
        run: |
          if [${{ secrets.SECRET }} == ""]; then
            echo "Secret is empty"
            exit 1
          fi
